### ISSUE TITLE
Cannot use SauceTestCase under Python 3

### ISSUE THREAD

**Issue by Ling** [appium/python-client#112]
Module 'new' was removed in Python 3 (deprecated since 2.6) and replaced with types.

python3 -m appium.saucetestcase
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/appium/saucetestcase.py", line 18, in <module>
    import new
ImportError: No module named 'new'

**Comment by imurchie** [comment]
Fixed by #113
