### ISSUE TITLE
pinch or zoom: Method has not yet been implemented

### ISSUE THREAD

**Issue by luiscruz** [appium/python-client#160]
When I try to use WebDriver.pinch or WebDriver.zoom methods, I get the following error:

```
Traceback (most recent call last):
  File "physalia-automators/appium_usecase.py", line 316, in <module>
    print pinch_and_spread_use_case.run().duration
  File "/Users/luiscruz/dev/physalia-automators/venv/lib/python2.7/site-packages/physalia/energy_profiler.py", line 63, in run
    self._run()
  File "physalia-automators/appium_usecase.py", line 300, in run_pinch_and_spread
    simple_routine()
  File "/Users/luiscruz/dev/physalia-automators/physalia-automators/utils.py", line 12, in repl
    return_value = fun(*args, **kwargs)
  File "physalia-automators/appium_usecase.py", line 297, in simple_routine
    use_case.driver.pinch(use_case.paint, percent=200, steps=50)
  File "/Users/luiscruz/dev/physalia-automators/venv/lib/python2.7/site-packages/appium/webdriver/webdriver.py", line 308, in pinch
    self.execute_script('mobile: pinchClose', opts)
  File "/Users/luiscruz/dev/physalia-automators/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 467, in execute_script
    'args': converted_args})['value']
  File "/Users/luiscruz/dev/physalia-automators/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/Users/luiscruz/dev/physalia-automators/venv/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented
```

Apparently Appium server claims that this method has not been implemented yet.

My Appium version:
```
> appium -v
1.6.3
```

**Comment by mykola-mokhnach** [comment]
You may try [mobile: *](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) as a workaround (Appium should be updated to 1.6.4-beta)

**Comment by luiscruz** [comment]
Thanks @mykola-mokhnach 
I have just updated Appium to 1.6.4 and I tried the following:

```
driver.execute_script(
    'mobile: pinch', {'id': element_id, 'scale': '0.5', 'velocity': 1}
)
``

I still get this error message:
```
Error: Message: Method has not yet been implemented
```
From the server log:
```
[HTTP] --> POST /wd/hub/session/f703e685-f512-4598-b6ac-bce5e643dde5/execute {"sessionId":"f703e685-f512-4598-b6ac-bce5e643dde5","args":[{"velocity":1,"scale":"0.5","id":"1"}],"script":"mobile: pinch"}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: pinch",[{"velocity":1,"scale":"0.5","id":"1"}],"f703e685-f512-4598-b6ac-bce5e643dde5"]
[HTTP] <-- POST /wd/hub/session/f703e685-f512-4598-b6ac-bce5e643dde5/execute 501 9 ms - 122
```

**Comment by mykola-mokhnach** [comment]
most likely you have something cached there. Make sure the version of XCUITest driver in the log is higher than 2.25

**Comment by KrishnaprabhaSNaik** [comment]
I am also getting similar error.  I am using Appium v1.7.0 . The used the following command:

locationpointer = "class=android.view.View"
AppiumLibrary.Zoom ${locationpointer} percent=200% steps=1

I am getting error: 
WebDriverException: Message: Method has not yet been implemented

Pls help !!

**Comment by ki4070ma** [comment]
Close because of https://github.com/appium/python-client/pull/358 .
