### ISSUE TITLE
Failed to switch context from native_app to web_view

### ISSUE THREAD

**Issue by Lanuet** [appium/python-client#255]
## The problem

Failed to switch context from native_app to web_view. I also clone your project and run test/functional/context_switching_tests.py, but i see the same issue. Pls help me.

## Environment
- Appium version (or git revision) that exhibits the issue: v1.9.0
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Window 10 x86_64
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: Android | 5.1.1
- Real device or emulator/simulator: real device
- Appium CLI or Appium.app|exe:

## Details
- start
- current_context = NATIVE_APP
- switch to: web_app
- I see the following error:
**  selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*18724
  (make sure the app has its WebView configured for debugging)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64) **

## Link to Appium Logs

[appium log]https://gist.github.com/Lanuet/9641d5e0e8a59da866e79565fb6fb3c4)

## Code To reproduce issue
web_view = context.driver.contexts[1]
context.driver.switch_to.context(web_view)

**Comment by KazuCocoa** [comment]
```
[W3C] Calling AppiumDriver.getContexts() with args: ["3bd5fe86-0796-44dd-9e7a-26df1d9accb7"]
[AndroidDriver] Getting a list of available webviews
[ADB] Running 'C:\Users\Teko\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s 5200e90dfa179400 shell cat /proc/net/unix'
[AndroidDriver] Found webviews: ["WEBVIEW_chrome"]
[AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_chrome"]
[W3C] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_chrome"]
[HTTP] <-- GET /wd/hub/session/3bd5fe86-0796-44dd-9e7a-26df1d9accb7/contexts 200 69 ms - 41
[HTTP] 
[HTTP] --> POST /wd/hub/session/3bd5fe86-0796-44dd-9e7a-26df1d9accb7/context
[HTTP] {"name":"WEBVIEW_chrome","sessionId":"3bd5fe86-0796-44dd-9e7a-26df1d9accb7"}
[W3C] Calling AppiumDriver.setContext() with args: ["WEBVIEW_chrome","3bd5fe86-0796-44dd-9e7a-26df1d9accb7"]
[AndroidDriver] Getting a list of available webviews
[ADB] Running 'C:\Users\Teko\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s 5200e90dfa179400 shell cat /proc/net/unix'
[AndroidDriver] Found webviews: ["WEBVIEW_chrome"]
[AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_chrome"]
[AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_chrome'
[AndroidDriver] A port was not given, using random port: 8000
[Chromedriver] Changed state to 'starting'
[Chromedriver] Found 1 executable in 'C:\Users\Lannt\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win'
[Chromedriver] The following Chromedriver executables were found:
[Chromedriver]     C:/Users/Lannt/AppData/Local/Programs/Appium/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe (minimum Chrome version '67.0.3396')
[ADB] Device API level: 22
[ADB] Getting package info for 'com.google.android.webview'
[ADB] Running 'C:\Users\Teko\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s 5200e90dfa179400 shell dumpsys package com.google.android.webview'
[Chromedriver] Found Chrome bundle 'com.google.android.webview' version '69.0.3497'
[Chromedriver] Found 1 Chromedriver executable capable of automating Chrome '69.0.3497'.
[Chromedriver] Choosing the most recent, 'C:/Users/Lannt/AppData/Local/Programs/Appium/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe'.
[Chromedriver] If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
[Chromedriver] Set chromedriver binary as: C:/Users/Lannt/AppData/Local/Programs/Appium/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe
[Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Cleaning any old adb forwarded port socket connections
[ADB] List forwarding ports
[ADB] Running 'C:\Users\Teko\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s 5200e90dfa179400 forward --list'
[Chromedriver] Spawning chromedriver with: C:/Users/Lannt/AppData/Local/Programs/Appium/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[Chromedriver] Chromedriver version: '2.41.578737'
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0.17134\"}}}"
[JSONWP Proxy] Matched '/session' to command name 'createSession'
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"io.selendroid.testapp","androidUseRunningApp":true,"androidDeviceSerial":"5200e90dfa179400"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"5445f5efe0fd51f2d3fa7509d6d4d1db","status":13,"value":{"message":"unknown error: Failed to get sockets matching: @webview_devtools_remote_.*20094\n  (make sure the app has its WebView configured for debugging)\n  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)"}}
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[Chromedriver] Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*20094
[Chromedriver]   (make sure the app has its WebView configured for debugging)
[Chromedriver]   (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)
[Chromedriver]     at Object.wrappedLogger.errorAndThrow (C:\Users\Lannt\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[Chromedriver]     at Chromedriver.callee$2$0$ (C:\Users\Lannt\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:448:13)
[Chromedriver]     at tryCatch (C:\Users\Lannt\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[Chromedriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Lannt\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[Chromedriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Lannt\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[Chromedriver]     at GeneratorFunctionPrototype.invoke (C:\Users\Lannt\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[Chromedriver]     at 
[JSONWP Proxy] Matched '/session' to command name 'createSession'
```

One question. Does the app enable webview debugging?

https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews

**Comment by mykola-mokhnach** [comment]
Are you able to debug the web view via chrome remote debugger?

**Comment by Lanuet** [comment]
yes, i can manual debug the web view via chrome remote debugger.
when my project run to select gmail (web view) i can see it at remote devices tab

**Comment by Lanuet** [comment]
Hi, i fixed this by add  'chromeOptions': {'androidPackage': 'com.android.chrome'} in dessired_caps {}
thank

**Comment by KazuCocoa** [comment]
Thanks!
It should be a good guide for others

**Comment by Nilesh61181** [comment]
@Lanuet 

can you help us getting the fix

I have tried these capabilites to make it work on UC browser dev apk.
DesiredCapabilities capabilities = new DesiredCapabilities();

		capabilities.setCapability("deviceName", "42100c599614a491");

		capabilities.setCapability("platformName", "Android");

		capabilities.setCapability("appPackage", "com.UCMobile.intl");
		capabilities.setCapability("appActivity", "com.UCMobile.main.UCMobile");
		capabilities.setCapability("noReset", true);
		capabilities.setCapability("showChromedriverLog",true); 
		ChromeOptions chromeOpt = new ChromeOptions();
		chromeOpt.setExperimentalOption("androidPackage","com.android.chrome");
		capabilities.setCapability(ChromeOptions.CAPABILITY,chromeOpt);
its still not working for me, we are using Appium 1.7.2 and java client4.1.2

**Comment by Lanuet** [comment]
```
desired_caps = {'platformName': context.config.userdata['platformName'],
                    'platformVersion': context.config.userdata['platformVersion'],
                    'deviceName': context.config.userdata['deviceName'],
                    'appPackage': settings['appPackage'],
                    'appActivity': settings['appActivity'],
                    'app': 'app.apk',
                    'browser': 'Chrome',
                    'chromeOptions': {'androidPackage': 'com.android.chrome'}}
```
i fixed that by add  'chromeOptions': {'androidPackage': 'com.android.chrome'}

**Comment by soum-test** [comment]
@mykola-mokhnach @Lanuet @KazuCocoa 

Guys, 

how to set this `'chromeOptions': {'androidPackage': 'com.android.chrome'}` using `DesiredCapabilities capabilities = new DesiredCapabilities();		
		capabilities.setCapability();` method?

I am not able to figure out how . Please guide me if you have any idea.
