### ISSUE TITLE
`def tap(self, positions, duration=None)` for python webdriver client is not working for android platform

### ISSUE THREAD

**Issue by DowneyTung** [appium/python-client#261]
## The problem

I am trying to use the tap method that provided in this [webdriver](https://github.com/appium/python-client/blob/master/appium/webdriver/webdriver.py) `line 493` file. It works fine for iOS simulators, but when I try to make it work for android platforms, it is showing the error saying the method is not implemented. 
Could you guys help to look at the stacktrace and confirm that the `tap` function is only working for ios platform? Or is there anyway we can use this concise `tap` function for  android platform?

## Environment
- Appium version (or git revision) that exhibits the issue: 1.9.1
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Saucelab
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: Android 7.0
- Real device or emulator/simulator:Galaxy S6
- Appium CLI or Appium.app|exe:

## Details

Here is the stack trace:
```
Traceback (most recent call last):
  File "/Users/dtung/Documents/vi_env/lib/python3.7/site-packages/golem/test_runner/test_runner.py", line 122, in run_test
    test_module.test(execution.data)
  File "/Users/dtung/Documents/vi_env/golem/H5G/projects/RMG/tests/mobile_game_click_on_spin_test.py", line 24, in test
    click_on_target_area_with_coordinates('spin_button', partner_game_lobby.base_element, execution.data['element_x_coordinate'], execution.data['element_y_coordinate'], client=execution.browser_definition['name'])
  File "/Users/dtung/Documents/vi_env/lib/python3.7/site-packages/golem/actions.py", line 660, in click_on_target_area_with_coordinates
    driver.tap(positions)
  File "/Users/dtung/Documents/vi_env/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 470, in tap
    action.perform()
  File "/Users/dtung/Documents/vi_env/lib/python3.7/site-packages/appium/webdriver/common/touch_action.py", line 94, in perform
    self._driver.execute(Command.TOUCH_ACTION, params)
  File "/Users/dtung/Documents/vi_env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/Users/dtung/Documents/vi_env/lib/python3.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
  File "/Users/dtung/Documents/vi_env/lib/python3.7/site-packages/appium/webdriver/errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "/Users/dtung/Documents/vi_env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented
```

**Comment by DowneyTung** [comment]
Is TouchActions implemented for Android at all for python client binding?

**Comment by DowneyTung** [comment]
find the issue, the touch action is not working if I run the appium test from on chrome with Android devices (however, it works for ios). A workaround for this is switching the context to NATIVE_APP and it will work then. For more details, please refer to this thread...
https://discuss.appium.io/t/touch-actions-and-mobile-web/795/8

In terms of how to set context, refer to this link:
http://appium.io/docs/en/commands/context/set-context/

**Comment by KazuCocoa** [comment]
thanks for the reference
