### ISSUE TITLE
Appium test not working due to incorrect import

### ISSUE THREAD

**Issue by clample** [appium/python-client#295]
## The problem

Appium tests with v0.33 of the Appium-Python-Client fail with

```
Traceback (most recent call last):
  File "appium_basic_test.py", line 3, in <module>
    from appium import webdriver
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/__init__.py", line 19, in <module>
    from .webdriver import WebDriver as Remote
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 31, in <module>
    from .extensions.context import Context
ModuleNotFoundError: No module named 'appium.webdriver.extensions'
```

## Code To reproduce issue

The test is a simple Appium test which can be found [here](https://github.com/saucelabs/appium-python-example/blob/fca57f28f98bdbfbf3b96057f206434949699b81/appium_basic_test.py)

**Comment by clample** [comment]
The full logs are:

```
+ pip install -U selenium
Collecting selenium
  Downloading https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904kB)
Collecting urllib3 (from selenium)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
Installing collected packages: urllib3, selenium
Successfully installed selenium-3.141.0 urllib3-1.24.1
[Pipeline] sh
+ pip install Appium-Python-Client
Collecting Appium-Python-Client
  Downloading https://files.pythonhosted.org/packages/be/66/3f7995230ea10334cc078d43eb64d35d8e82815961d24f15e43085039ba3/Appium-Python-Client-0.33.tar.gz
Requirement already satisfied: selenium>=3.14.1 in /usr/local/lib/python3.7/site-packages (from Appium-Python-Client) (3.141.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/site-packages (from selenium>=3.14.1->Appium-Python-Client) (1.24.1)
Building wheels for collected packages: Appium-Python-Client
  Running setup.py bdist_wheel for Appium-Python-Client: started
  Running setup.py bdist_wheel for Appium-Python-Client: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/66/77/a1/3c7bdee211bb60324f50b666853d9a03a0b0b32888ac0fec8d
Successfully built Appium-Python-Client
Installing collected packages: Appium-Python-Client
Successfully installed Appium-Python-Client-0.33
[Pipeline] sh
+ python appium_basic_test.py
Traceback (most recent call last):
  File "appium_basic_test.py", line 3, in <module>
    from appium import webdriver
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/__init__.py", line 19, in <module>
    from .webdriver import WebDriver as Remote
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 31, in <module>
    from .extensions.context import Context
ModuleNotFoundError: No module named 'appium.webdriver.extensions'
```

**Comment by KazuCocoa** [comment]
thanks! I'm working for it

**Comment by clample** [comment]
Sounds good, thanks @KazuCocoa

**Comment by KazuCocoa** [comment]
![image](https://user-images.githubusercontent.com/5511591/50146207-97975b00-02f6-11e9-9d5a-3c2ea1943358.png)


could you try 0.34? I ensured the module exists in 0.34 as attached image.
@clample 

Thanks for your report, again
