### ISSUE TITLE
set_clipboard error

### ISSUE THREAD

**Issue by JamCh01** [appium/python-client#339]
## The problem

set_clipboard() cannot be used in Chinese or emoji.

## Environment
- Appium version (or git revision) that exhibits the issue: 1.10.0 
- Last Appium version that did not exhibit the issue (if applicable): No
- Desktop OS/version used to run Appium: macOS Mojave 10.14.3
- Node.js version (unless using Appium.app|exe): v11.9.0
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Real device 
- Appium CLI or Appium.app|exe: Appium.app

## Details
The same problem will occur when use get_clipboard()

## Link to Appium Logs
here is the Python code error
```
Traceback (most recent call last):
  File "tiktok_spider.py", line 114, in <module>
    test()
  File "tiktok_spider.py", line 109, in test
    tiktok.get_video_info(_input='#在抖音，记录美好生活##我们都是追梦人 😊😊😊 http://v.douyin.com/YnQw33/ 复制此链接，打开【抖音短视频】，直接观看视频！')
  File "tiktok_spider.py", line 98, in get_video_info
    self.driver.set_clipboard_text(_input)
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/extensions/clipboard.py", line 51, in set_clipboard_text
    self.set_clipboard(appium_bytes(str(text), 'UTF-8'), ClipboardContentType.PLAINTEXT, label)
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/extensions/clipboard.py", line 41, in set_clipboard
    self.execute(Command.SET_CLIPBOARD, options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented
```
and here is thr appium log
```
[W3C (8fe12749)] Calling AppiumDriver.setClipboard() with args: ["I+WcqOaKlumfs++8jOiusOW9lee+juWlveeUn+a0uyMj5oiR5Lus6YO95piv6L+95qKm5Lq6IFUrMUY2MEFVKzFGNjBBVSsxRjYwQSBodHRwOi8vdi5kb3V5aW4uY29tL1luUXczMy8g5aSN5Yi25q2k6ZO+5o6l77yM5omT5byA44CQ5oqW6Z+z55+t6KeG6aKR44CR77yM55u05o6l6KeC55yL6KeG6aKR77yB","plaintext",null,"8fe12749-e06f-4c76-bf08-e7b699187ad9",null,"8fe12749-e06f-4c76-bf08-e7b699187ad9"]
[W3C (8fe12749)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[W3C (8fe12749)]     at AndroidDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/basedriver/driver.js:261:13)
[W3C (8fe12749)]     at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:425:36)
[W3C (8fe12749)]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session/8fe12749-e06f-4c76-bf08-e7b699187ad9/appium/device/set_clipboard 404 2 ms - 504
```

**Comment by mykola-mokhnach** [comment]
This is expected. The endpoint is only supported by UAI2/Espresso

**Comment by JamCh01** [comment]
@mykola-mokhnach thanks for your reply, so can you give me some advice about doing this job?

**Comment by mykola-mokhnach** [comment]
I did. Fix the automation backend

**Comment by JamCh01** [comment]
@mykola-mokhnach sorry, I didn't understand your means...

**Comment by mykola-mokhnach** [comment]
http://appium.io/docs/en/drivers/android-uiautomator2/

**Comment by JamCh01** [comment]
@mykola-mokhnach Thanks, I'll try it~
