### ISSUE TITLE
Unable to install Appium Python Client on CentOS 7.6 64bit

### ISSUE THREAD

**Issue by goranc** [appium/python-client#397]
## The problem

Can't install versions 0.43 or 0.44 o standard CentOS 7.6 with python 2.7.5

## Environment
- Appium version (or git revision) that exhibits the issue: 0.43 or 0.44
- Last Appium version that did not exhibit the issue (if applicable): 0.42
- Desktop OS/version used to run Appium: centos 7.6 64bit
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:

## Details
```
Collecting Appium-Python-Client
  Using cached https://files.pythonhosted.org/packages/e6/56/dc176410778a2fd31ad66360101c8dac087070d55bb5cf9b88ef22ad2af4/Appium-Python-Client-0.44.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-iuH4o_/Appium-Python-Client/setup.py", line 37, in <module>
        packages=find_packages(include=['appium*']),
    TypeError: find_packages() got an unexpected keyword argument 'include'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-iuH4o_/Appium-Python-Client/
```

## Code To reproduce issue
sudo pip install Appium-Python-Client

**Comment by ki4070ma** [comment]
@goranc 

Which version of setuptools do you use?

```
pip show setuptools
```

if it's old, please try this.
https://github.com/quantopian/zipline/issues/1278

**Comment by ki4070ma** [comment]
I could install with below versions.

```
➜  python-client git:(fix-flaky-tests) ✗ python --version
Python 2.7.5
➜  python-client git:(fix-flaky-tests) ✗ pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package    Version
---------- -------
pip        19.1.1 
setuptools 41.0.1 
wheel      0.33.4 
➜  python-client git:(fix-flaky-tests) ✗ pip install Appium-Python-Client
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting Appium-Python-Client
/Users/atsushimori/.pyenv/versions/2.7.5/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:354: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/Users/atsushimori/.pyenv/versions/2.7.5/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:150: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Using cached https://files.pythonhosted.org/packages/e6/56/dc176410778a2fd31ad66360101c8dac087070d55bb5cf9b88ef22ad2af4/Appium-Python-Client-0.44.tar.gz
Collecting selenium<4,>=3.14.1 (from Appium-Python-Client)
  Using cached https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl
Collecting urllib3 (from selenium<4,>=3.14.1->Appium-Python-Client)
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Building wheels for collected packages: Appium-Python-Client
  Building wheel for Appium-Python-Client (setup.py) ... done
  Stored in directory: /Users/atsushimori/Library/Caches/pip/wheels/8d/9c/46/7fbc7afba8607cfce07390d555e54f49a1b962175d4a580fb8
Successfully built Appium-Python-Client
Installing collected packages: urllib3, selenium, Appium-Python-Client
Successfully installed Appium-Python-Client-0.44 selenium-3.141.0 urllib3-1.25.3
➜  python-client git:(fix-flaky-tests) ✗ 
```

**Comment by KazuCocoa** [comment]
So, we should follow either:

- Add `setuptools` in readme
- Back to the previous syntax

What about Selenium Python, btw?
(no need to update setuptools?)

**Comment by ki4070ma** [comment]
@KazuCocoa 

At least `include` option exists 5 years ago.
So I think we don't need both. (but if necessary, I'll take former one.)
It's better not to take care of packages changes in `setup.py`.

https://github.com/pypa/setuptools/commit/db165ca67c638fdcae9b3a85154b2b4b23e3f5db

> What about Selenium Python, btw?
> (no need to update setuptools?)

Yes, they don't need to update setuptools since it's same to our previous syntax.

https://github.com/SeleniumHQ/selenium/blob/master/py/setup.py#L53

Any further comments are welcome.

**Comment by ki4070ma** [comment]
Not active.
If additional info, please freely re-open.
