### ISSUE TITLE
remove pipfile to reduce pipenv issues

### ISSUE THREAD

**Issue by KazuCocoa** [appium/python-client#400]
When I did a workshop at the AppiumConf 2019, resolve dependencies error happened in pipenv. (Following README)
Once backed to the previous implementation, it resolved.
The guy uses pucyarm etc so maybe some dependencies became conflicted

https://github.com/appium/python-client/pull/376

(update later)

**Comment by ki4070ma** [comment]
@KazuCocoa 

Might be my mistakes.
If necessary, please try below.

```
 pip install --user pipenv
 python -m pipenv lock --clear
 python -m pipenv install --dev --system
```

**Comment by KazuCocoa** [comment]
When he ran `py.test test/unit`, no `import httpretty` is raised since the command could not resolve dependencies. After running as `python -m py.test test/unit`, I forgot but another dependencies error raised.

Let me try to reproduce it later...

**Comment by VinayakaMayura** [comment]
When i try 

> python -m pipenv lock --clear

It gives below error

```➜  python-client git:(master) ✗ python -m pipenv lock --clear 
Locking [dev-packages] dependencies…
✘ Locking Failed! 
Traceback (most recent call last):
  File "/Users/vinaymgg/Library/Python/3.7/lib/python/site-packages/pipenv/resolver.py", line 124, in <module>
    from pipenv.vendor import colorama
  File "/Users/vinaymgg/Library/Python/3.7/lib/python/site-packages/pipenv/__init__.py", line 22, in <module>
    from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
  File "/Users/vinaymgg/Library/Python/3.7/lib/python/site-packages/pipenv/vendor/vistir/__init__.py", line 18, in <module>
    from .misc import (
  File "/Users/vinaymgg/Library/Python/3.7/lib/python/site-packages/pipenv/vendor/vistir/misc.py", line 515, in <module>
    PREFERRED_ENCODING = getpreferredencoding()
  File "/Users/vinaymgg/Library/Python/3.7/lib/python/site-packages/pipenv/vendor/vistir/misc.py", line 509, in getpreferredencoding
    _default_encoding = locale.getdefaultlocale()[1]
  File "/Users/vinaymgg/.local/share/virtualenvs/python-client-kx7E6_fq/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/vinaymgg/.local/share/virtualenvs/python-client-kx7E6_fq/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
File "/Users/vinaymgg/Library/Python/3.7/lib/python/site-packages/pipenv/resolver.py", line 124, in <module>
    from pipenv.vendor import colorama
  File "/Users/vinaymgg/Library/Python/3.7/lib/python/site-packages/pipenv/__init__.py", line 22, in <module>
    from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
  File "/Users/vinaymgg/Library/Python/3.7/lib/python/site-packages/pipenv/vendor/vistir/__init__.py", line 18, in <module>
    from .misc import (
  File "/Users/vinaymgg/Library/Python/3.7/lib/python/site-packages/pipenv/vendor/vistir/misc.py", line 515, in <module>
    PREFERRED_ENCODING = getpreferredencoding()
  File "/Users/vinaymgg/Library/Python/3.7/lib/python/site-packages/pipenv/vendor/vistir/misc.py", line 509, in getpreferredencoding
    _default_encoding = locale.getdefaultlocale()[1]
  File "/Users/vinaymgg/.local/share/virtualenvs/python-client-kx7E6_fq/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/vinaymgg/.local/share/virtualenvs/python-client-kx7E6_fq/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by mykola-mokhnach** [comment]
https://github.com/pypa/pipenv/issues/187

**Comment by ki4070ma** [comment]
Thanks @mykola-mokhnach 

However, we don't expect setting up env has error for contributor.
We can take two options. If no problem, I'll take the former one.

1. Add how to fix to readme
2. Back to the previous style

@KazuCocoa 
Do you have any feedbacks to above options from your workshop point of view?
(e.g. too many people had same problem, so simply back to the previous style.)

**Comment by mykola-mokhnach** [comment]
Lets try with readme first. If still does not work then we always can revert it

**Comment by KazuCocoa** [comment]
Agree > readme first

@VinayakaMayura Could you try https://github.com/appium/python-client/issues/400#issuecomment-502020979 once on your environment?

**Comment by VinayakaMayura** [comment]
@KazuCocoa @mykola-mokhnach [https://github.com/appium/python-client/issues/400#issuecomment-502020979](#400 (comment)  this works fine

**Comment by KazuCocoa** [comment]
thanks. We'll add doc in #403 so far

**Comment by 0mars** [comment]
having the same issue, and none of the solutions work, guess it popped up differently now

```
 pipenv install           
Pipfile.lock (46359b) out of date, updating to (ed9505)…
Locking [dev-packages] dependencies…
✘ Locking Failed! 
Traceback (most recent call last):
  File "/home/omar/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 124, in <module>
    from pipenv.vendor import colorama
  File "/home/omar/workspace/python/talks/packages/stars/.venv/lib/python3.7/site-packages/pipenv/__init__.py", line 47, in <module>

```
