### ISSUE TITLE
Message: A new session could not be created. Details: Appium's IosDriver does not support Xcode version 11.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.

### ISSUE THREAD

**Issue by liuchengxu11** [appium/python-client#442]
## The problem

在xcode更新到11之后接连遇到许多问题，一路踩坑到现在好不容易 appium-desktop的能够正确出现app并能够识别元素了。但是现在想用pycharm使用python直接调用appium写自动化代码显示如标题的错误说现在ios的驱动无法支持xcode11.想问下各位有没有什么别的办法能解决一下
## Environment

python本地的环境如下
python 3.7.4 
appium  版本  Appium v1.15.0-rc.5
Appium-Python-Client==0.47
atomicwrites==1.3.0
attrs==19.1.0
autopep8==1.4.4
certifi==2019.9.11
chardet==3.0.4
configparser==4.0.2
contextlib2==0.5.5
Django==1.11.24
docopt==0.6.2
funcsigs==1.0.2
idna==2.8
importlib-metadata==0.23
more-itertools==5.0.0
packaging==19.2
pathlib2==2.3.4
pipreqs==0.4.9
pluggy==0.13.0
ptest==1.9.5
py==1.8.0
pycodestyle==2.5.0
pyparsing==2.4.2
pytest==4.6.5
pytest-html==1.22.0
pytest-metadata==1.8.0
pytz==2019.2
requests==2.22.0
scandir==1.10.0
selenium==3.141.0
six==1.12.0
urllib3==1.25.3
wcwidth==0.1.7
yarg==0.1.9
zipp==0.6.0

## Details

报错截图就是最基本的调用程序
![image](https://user-images.githubusercontent.com/33363646/65749427-9ffbac80-e138-11e9-821d-a374f9b704bd.png)

**Comment by liuchengxu11** [comment]
> Also python client has nice set of functional tests, where you could borrow code examples: https://github.com/appium/python-client/tree/master/test/functional/ios

Thank! Sir! Python's client is in my environment. I would like to ask when appium 1.15 will be released as a stable version. I'm using incompatible Xcode 11.

**Comment by KazuCocoa** [comment]
You put `automationName` twice. The first is `xcuites` (ok) and the seconds is `appium`. You should remove the second one.

**Comment by liuchengxu11** [comment]
> 你放了`automationName`两次。第一个是`xcuites`（ok），第二个是`appium`。您应该删除第二个。

Thank you, sir, but I have a new error after I update 1.15.

**Comment by liuchengxu11** [comment]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fcd4821da10>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuchengxu/work/pycharm-package/appium_ios/ios.py", line 35, in <module>
    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 144, in __init__
    proxy
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 219, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 762, in urlopen
    **response_kw
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcd4821da10>: Failed to establish a new connection: [Errno 61] Connection refused'))

**Comment by liuchengxu11** [comment]
![image](https://user-images.githubusercontent.com/33363646/65776758-4f567480-e175-11e9-98fd-bcb76abdc36e.png)

The first line of the code locates this. Does anyone know what the problem is?

**Comment by liuchengxu11** [comment]
> python客户端也有一组不错的功能测试，您可以在其中借用代码示例：[https](https://github.com/appium/python-client/tree/master/test/functional/ios) : [//github.com/appium/python-client/tree/master/test/functional/ios](https://github.com/appium/python-client/tree/master/test/functional/ios)

Hey, Mr. Hey, can you help me see the following mistakes? I don't understand.

**Comment by KazuCocoa** [comment]
Could you share the Appium server-side log to see the cause deeply?

**Comment by liuchengxu11** [comment]
> 您能否共享Appium服务器端日志以深入了解原因？


谢谢先生  问题现在我以解决了
Thank you, sir. Now I have solved the problem.

**Comment by KazuCocoa** [comment]
👍
