### ISSUE TITLE
self.driver.events throws exception

### ISSUE THREAD

**Issue by ki4070ma** [appium/python-client#467]
## The problem

`self.driver.events` throws exception

## Environment
- Appium version (or git revision) that exhibits the issue: 1.16.0-beta.1
- Last Appium version that did not exhibit the issue (if applicable): --
- Desktop OS/version used to run Appium: Mac 10.15.1
- Node.js version (unless using Appium.app|exe): v12.8.0
- Mobile platform/version under test: Android 8.0
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: CLI

## Details

```
$python SampleAndroidTest.py
testtest (__main__.SampleAndroidTest) ... *****
--- Logging error ---
Traceback (most recent call last):
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/site-packages/Appium_Python_Client-0.48-py3.8.egg/appium/webdriver/webdriver.py", line 419, in events
    return self.session['events']
KeyError: 'events'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "SampleAndroidTest.py", line 102, in <module>
    unittest.TextTestRunner(verbosity=2).run(suite)
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "SampleAndroidTest.py", line 82, in testtest
    print(self.driver.events)
  File "/Users/atsushimori/.pyenv/versions/3.8.0/lib/python3.8/site-packages/Appium_Python_Client-0.48-py3.8.egg/appium/webdriver/webdriver.py", line 421, in events
    logger.warning('Could not find events information in the session. Error:', e)
Message: 'Could not find events information in the session. Error:'
Arguments: (KeyError('events'),)
{}
ok

----------------------------------------------------------------------
Ran 1 test in 15.329s

OK

```

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by mykola-mokhnach** [comment]
I would say the error is expected for W3C protocol. We need to switch this endpoint to the custom route according to https://github.com/appium/appium/issues/13568

**Comment by ki4070ma** [comment]
@mykola-mokhnach 
Thanks, you're right, it's my misunderstanding.
