### ISSUE TITLE
Install failing for v1.0.0

### ISSUE THREAD

**Issue by abhijithshaji** [appium/python-client#541]
## The problem

Installion for Appium-Python-Client 1.0.0 is failing, tried `pip install Appium-Python-Client` and Installing from tarball, both greeted with the same following error:

`$pip install Appium-Python-Client`

```DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting Appium-Python-Client
  Using cached Appium-Python-Client-1.0.0.tar.gz (51 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/abhi/.pyenv/versions/2.7.17/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1t/yxydn3z14633322zns_jz2br0000gn/T/pip-install-uc43Rh/Appium-Python-Client/setup.py'"'"'; __file__='"'"'/private/var/folders/1t/yxydn3z14633322zns_jz2br0000gn/T/pip-install-uc43Rh/Appium-Python-Client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/1t/yxydn3z14633322zns_jz2br0000gn/T/pip-pip-egg-info-OSMsNe
         cwd: /private/var/folders/1t/yxydn3z14633322zns_jz2br0000gn/T/pip-install-uc43Rh/Appium-Python-Client/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1t/yxydn3z14633322zns_jz2br0000gn/T/pip-install-uc43Rh/Appium-Python-Client/setup.py", line 19, in <module>
        from appium.common.helper import library_version
      File "appium/common/helper.py", line 20
        def extract_const_attributes(cls: type) -> Dict[str, Any]:
                                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## Environment
- Appium version (or git revision) that exhibits the issue: 1.0.0
- Last Appium version that did not exhibit the issue (if applicable): 0.52
- Desktop OS/version used to run Appium: macOS 10.15.4
- python: 2.7.17, 2.7.16
- pip: 20.1 & 18.1

## Details

Install works with `pip install Appium-Python-Client==0.52

**Comment by shibupanda** [comment]
@abhijithshaji 
Seems it drops py2 support. 
This version require Support 3.7+ as per the changelog
https://github.com/appium/python-client/commit/dcc54d94fe84383a5aca46b143c4870981eb5dd4#diff-de0a9b67ffe2874a076b5fdb15bad484R40

**Comment by KazuCocoa** [comment]
Yes, 1.0.0 support only Python 3 as addressed in Notice https://pypi.org/project/Appium-Python-Client/

Please use 0.x for Python 2.

**Comment by KazuCocoa** [comment]
The Python2 branch is https://github.com/appium/python-client/tree/python2

**Comment by kaustubh275** [comment]
Use **pip install Appium-Python-Client==0.52** for python 2.
