### ISSUE TITLE
Error when executing shell command to stream screen

### ISSUE THREAD

**Issue by napsta32** [appium/python-client#558]
## The problem

I want to stream screen using appium tutorial but I receive this error each time I try:

```
[W3C (c24da021)] Calling AppiumDriver.execute() with args: ["mobile: shell",[{"considerRotation":true,"quality":45,"bitRate":500000,"tcpPort":8094}],"abc-xyz-123"]
[AndroidDriver] Executing native command 'mobile: shell'
[AndroidDriver] The 'command' argument is mandatory'
[W3C (c24da021)] Encountered internal error running command: Error: The 'command' argument is mandatory'
[W3C (c24da021)]     at Object.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:87:35)
[W3C (c24da021)]     at AndroidUiautomator2Driver.mobileShell (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/shell.js:21:9)
[W3C (c24da021)]     at AndroidUiautomator2Driver.executeMobile (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/commands/general.js:142:16)
[W3C (c24da021)]     at AndroidUiautomator2Driver.execute (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/execute.js:11:23)
[W3C (c24da021)]     at commandExecutor (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:330:9)
[W3C (c24da021)]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:125:12
[W3C (c24da021)]     at AsyncLock._promiseTry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:249:31)
[W3C (c24da021)]     at exec (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:124:9)
[W3C (c24da021)]     at AsyncLock.acquire (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:140:3)
[W3C (c24da021)]     at AndroidUiautomator2Driver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:343:39)
[W3C (c24da021)]     at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:534:36)
[W3C (c24da021)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[W3C (c24da021)]     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:309:21)
[HTTP] <-- POST /wd/hub/session/abc-xyz-123/execute/sync 500 12 ms - 635
[HTTP] 
```

## Environment
- Appium Desktop Server v1.17.1
- Appium Python Client 1.0.1
- macOS Catalina 10.15.4
- Android Pixel 3 Emulator

## Code To reproduce issue

```
driver.execute_script('mobile: shell', {
            'considerRotation': True,
            'quality': 45,
            'bitRate': 500000,
            'tcpPort': 8094,
 })
```

**Comment by ki4070ma** [comment]
@napsta32 

I hope it helps you.
https://github.com/ki4070ma/vui-automation-playground/blob/master/device/device.py#L21

**Comment by napsta32** [comment]
Yes it is this one: http://appium.io/docs/en/writing-running-appium/android/android-screen-streaming/

I found the error.
Code should be:

```
driver.execute_script('mobile: startScreenStreaming', {...
```

**Comment by napsta32** [comment]
I created this PR to update doc https://github.com/appium/appium/pull/14653

**Comment by napsta32** [comment]
its merged. thanks for the help @ki4070ma it gave me a hint of what was going on.
