### ISSUE TITLE
ERROR CAPABILITIES

### ISSUE THREAD

**Issue by luishrdzusieto** [appium/python-client#568]
## The problem

I cant import the capabilities from JSON

My capabilities: 
    def setUp(self):
        with open("../Data/data.json",encoding="utf-8") as data_file:
            data = json.loads(data_file.read())
        self.desired_cap = {
            "deviceName": "RF8N91R7F7X",
            "platformName": "Android",
            "app": "C:\\eWorker\\APK\\app-debug-22-12.apk",
            "appPackage": "com.enel.mobile.eworker",
            "appWaitActivity": "com.enel.mobile.eworker.MainActivity"
            }

        print(self.desired_cap)

        # DRIVER
        self.driver = webdriver.Remote("http://localhost:4723/wd/hub", self.desired_cap)
        self.driver.implicitly_wait(30)

Without JSON its works:
    def setUp(self):
        with open("../Data/data.json",encoding="utf-8") as data_file:
            data = json.loads(data_file.read())
        self.desired_cap = {
            "deviceName": "RF8N91R7F7X",
            "platformName": "Android",
            "app": "C:\\eWorker\\APK\\app-debug-22-12.apk",
            "appPackage": "com.enel.mobile.eworker",
            "appWaitActivity": "com.enel.mobile.eworker.MainActivity"
            }

        print(self.desired_cap)

        # DRIVER
        self.driver = webdriver.Remote("http://localhost:4723/wd/hub", self.desired_cap)
        self.driver.implicitly_wait(30)

THE ERROR:
Error
Traceback (most recent call last):
  File "C:\Users\luish\AppData\Local\Programs\Python\Python38-32\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\luish\AppData\Local\Programs\Python\Python38-32\lib\unittest\case.py", line 672, in run
    self._callSetUp()
  File "C:\Users\luish\AppData\Local\Programs\Python\Python38-32\lib\unittest\case.py", line 630, in _callSetUp
    self.setUp()
  File "C:\Users\luish\PycharmProjects\AppiumTest\Pruebas\Test4(JSON).py", line 23, in setUp
    self.driver = webdriver.Remote("http://localhost:4723/wd/hub", desired_cap)
  File "C:\Users\luish\PycharmProjects\AppiumTest\venv\lib\site-packages\appium\webdriver\webdriver.py", line 151, in __init__
    super().__init__(
  File "C:\Users\luish\PycharmProjects\AppiumTest\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\luish\PycharmProjects\AppiumTest\venv\lib\site-packages\appium\webdriver\webdriver.py", line 225, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "C:\Users\luish\PycharmProjects\AppiumTest\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luish\PycharmProjects\AppiumTest\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\eWorker\eworker_QA_1.11.0.apk' does not exist or is not accessible

Assertion failed

Assertion failed
C:\Users\luish\AppData\Local\Programs\Python\Python38-32\lib\unittest\case.py:704: ResourceWarning: unclosed <socket.socket fd=512, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 57541), raddr=('127.0.0.1', 4723)>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback

Ran 1 test in 2.061s

FAILED (errors=1)

Process finished with exit code 1

## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
Please attach the full appium server log.

_My capabilities:_ and _Without JSON its works:_ seem the same.
Did you mean your parsed JSON data was wrong?

**Comment by luishrdzusieto** [comment]
# CAPABILITIES

data_file = open("../Data/data.json", "r")
jsondata = data_file.read()
data = json.loads(jsondata)

desired_cap = {"deviceName": data["deviceName"],
               "platformName": data["platformName"],
               "app": data["app"],
               "appPackage": data["appPackage"],
               "appWaitActivity": data["appWaitActivity"]
               }

print(desired_cap["deviceName"])


driver = webdriver.Remote("http://localhost:4723/wd/hub", desired_cap)

JSON:
{
  "deviceName": "RF8N91R7F7X",
  "platformName": "Android",
  "appPackage": "com.enel.mobile.eworker",
  "appWaitActivity": "com.enel.mobile.eworker.MainActivity",
  "app": "C:\\eWorker\\eworker_QA_1.11.0.apk"

}
ERROR:
C:\Users\luish\PycharmProjects\AppiumTest\venv\Scripts\python.exe C:/Users/luish/PycharmProjects/AppiumTest/Pruebas/ID4-DETALLES_AVISOS_PRUEBAJSON.py
RF8N91R7F7X
Traceback (most recent call last):
  File "C:/Users/luish/PycharmProjects/AppiumTest/Pruebas/ID4-DETALLES_AVISOS_PRUEBAJSON.py", line 23, in <module>
    driver = webdriver.Remote("http://localhost:4723/wd/hub", desired_cap)
  File "C:\Users\luish\PycharmProjects\AppiumTest\venv\lib\site-packages\appium\webdriver\webdriver.py", line 151, in __init__
    super().__init__(
  File "C:\Users\luish\PycharmProjects\AppiumTest\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\luish\PycharmProjects\AppiumTest\venv\lib\site-packages\appium\webdriver\webdriver.py", line 225, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "C:\Users\luish\PycharmProjects\AppiumTest\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luish\PycharmProjects\AppiumTest\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\eWorker\eworker_QA_1.11.0.apk' does not exist or is not accessible


Process finished with exit code 1

**Comment by KazuCocoa** [comment]
> Please attach the full appium server log.

Could you attach the server-side log as well?
You attached only the client-side error log, but we need the appium server-side to clarify what data was sent.
(GIST is preferred as the description's _Link to Appium Logs_ section)

**Comment by ki4070ma** [comment]
Closed as not active
