### ISSUE TITLE
[Mac2Driver] How to get the attribute value of an element?

### ISSUE THREAD

**Issue by thinhndfloware** [appium/python-client#625]
Hi guys,

I've been using appium-mac2-driver + Python + selenium and impossible to get the value of an element's attribute. It showed an error that said the method is not implemented (see the attached screenshot).

As far as I know that the error is very clear and we have not supported it yet. A current solution from me is that I get page source and then find the element with all attributes. Could you please advise on another way to get the value of an element's attribute from a WebElement object?

Thank you so much.

## Environment
- Appium version 1.21.0
- MacOS Catalina 10.15.7
- Node.js version 12.18.1:
- Appium-Python-Client version 1.2.0

## Link to Appium Logs

2021-08-15 12:12:46:949 [Appium] Welcome to Appium v1.21.0
2021-08-15 12:12:46:950 [Appium] Non-default server args:
2021-08-15 12:12:46:950 [Appium]   address: localhost
2021-08-15 12:12:46:950 [Appium]   port: 4724
2021-08-15 12:12:46:950 [Appium]   logFile: /Users/thinhnguyen/_github/auto-mac/logs/appium.log
2021-08-15 12:12:46:971 [Appium] Appium REST http interface listener started on localhost:4724
2021-08-15 12:12:47:676 [HTTP] --> HEAD /wd/hub/status
2021-08-15 12:12:47:677 [HTTP] {}
2021-08-15 12:12:47:678 [GENERIC] Calling AppiumDriver.getStatus() with args: []
2021-08-15 12:12:47:679 [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.21.0"}}
2021-08-15 12:12:47:684 [HTTP] <-- HEAD /wd/hub/status 200 6 ms - 68
2021-08-15 12:12:47:684 [HTTP] 
2021-08-15 12:12:47:713 [HTTP] --> POST /wd/hub/session
2021-08-15 12:12:47:714 [HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"mac","appium:automationName":"mac2","appium:newCommandTimeout":30000,"appium:bundleId":"com.mycompany"}},"desiredCapabilities":{"platformName":"mac","appium:automationName":"mac2","appium:newCommandTimeout":30000,"appium:bundleId":"com.mycompany"}}
2021-08-15 12:12:47:714 [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"mac","appium:automationName":"mac2","appium:newCommandTimeout":30000,"appium:bundleId":"com.mycompany"},null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"mac","appium:automationName":"mac2","appium:newCommandTimeout":30000,"appium:bundleId":"com.mycompany"}}]
2021-08-15 12:12:47:715 [BaseDriver] Event 'newSessionRequested' logged at 1629029567714 (19:12:47 GMT+0700 (Indochina Time))
2021-08-15 12:12:47:806 [Appium] Appium v1.21.0 creating new Mac2Driver (v0.13.0) session
2021-08-15 12:12:47:807 [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
2021-08-15 12:12:47:807 [BaseDriver] Creating session with W3C capabilities: {
2021-08-15 12:12:47:807 [BaseDriver]   "alwaysMatch": {
2021-08-15 12:12:47:807 [BaseDriver]     "platformName": "mac",
2021-08-15 12:12:47:808 [BaseDriver]     "appium:automationName": "mac2",
2021-08-15 12:12:47:808 [BaseDriver]     "appium:newCommandTimeout": 30000,
2021-08-15 12:12:47:808 [BaseDriver]     "appium:bundleId": "com.mycompany"
2021-08-15 12:12:47:808 [BaseDriver]   },
2021-08-15 12:12:47:808 [BaseDriver]   "firstMatch": [
2021-08-15 12:12:47:808 [BaseDriver]     {}
2021-08-15 12:12:47:808 [BaseDriver]   ]
2021-08-15 12:12:47:808 [BaseDriver] }
2021-08-15 12:12:47:810 [BaseDriver] Session created with session id: 0a732e24-1c73-4dc0-b796-ff6f241e34ee
2021-08-15 12:12:47:811 [WebDriverAgentMac] Using bootstrap root: /usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/WebDriverAgentMac
2021-08-15 12:12:47:812 [WebDriverAgentMac] Using xcodebuild binary at '/usr/bin/xcodebuild'
2021-08-15 12:12:47:815 [WebDriverAgentMac] WebDriverAgent sources are up to date (1628736193669 >= 1628736193669)
2021-08-15 12:12:47:815 [WebDriverAgentMac] Using 127.0.0.1 as server host
2021-08-15 12:12:47:815 [WebDriverAgentMac] Using port 10100
2021-08-15 12:12:47:817 [WebDriverAgentMac] The port #10100 at 127.0.0.1 is busy. Assuming it is an obsolete WDA server instance and trying to terminate it in order to start a new one
2021-08-15 12:12:49:367 [WebDriverAgentMac] The previously running WDA server has been successfully terminated after 1549ms
2021-08-15 12:12:49:369 [WebDriverAgentMac] Mac2Driver host process logging is disabled. All the xcodebuild output is going to be suppressed. Set the 'showServerLogs' capability to 'true' if this is an undesired behavior
2021-08-15 12:12:49:370 [WebDriverAgentMac] Starting Mac2Driver host process: xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentMac.xcodeproj -scheme WebDriverAgentRunner COMPILER_INDEX_STORE_ENABLE\=NO
2021-08-15 12:12:49:383 [WD Proxy] Matched '/status' to command name 'getStatus'
2021-08-15 12:12:49:385 [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
2021-08-15 12:12:49:389 [WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
2021-08-15 12:12:50:390 [WD Proxy] Matched '/status' to command name 'getStatus'
2021-08-15 12:12:50:391 [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
2021-08-15 12:12:50:392 [WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
2021-08-15 12:12:51:393 [WD Proxy] Matched '/status' to command name 'getStatus'
2021-08-15 12:12:51:393 [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
2021-08-15 12:12:51:394 [WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
2021-08-15 12:12:52:398 [WD Proxy] Matched '/status' to command name 'getStatus'
2021-08-15 12:12:52:398 [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
2021-08-15 12:12:52:399 [WD Proxy] connect ECONNREFUSED 127.0.0.1:10100
2021-08-15 12:12:53:405 [WD Proxy] Matched '/status' to command name 'getStatus'
2021-08-15 12:12:53:406 [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
2021-08-15 12:12:53:414 [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"version":"Version 10.15.7 (Build 19H114)"},"ready":true,"build":{"time":"Aug 15 2021 10:55:51"}},"sessionId":null}
2021-08-15 12:12:53:490 [WebDriverAgentMac] The host process is ready within 4109ms
2021-08-15 12:12:53:491 [WD Proxy] Matched '/session' to command name 'createSession'
2021-08-15 12:12:53:491 [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:10100/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"mac","automationName":"mac2","newCommandTimeout":30000,"bundleId":"com.mycompany"}}}
2021-08-15 12:12:54:732 [WD Proxy] Got response with status 200: {"value":{"sessionId":"8328BD9E-22C9-4868-88D4-6B81113F6203","capabilities":{"CFBundleIdentifier":"com.mycompany"}},"sessionId":"8328BD9E-22C9-4868-88D4-6B81113F6203"}
2021-08-15 12:12:54:732 [WD Proxy] Determined the downstream protocol as 'W3C'
2021-08-15 12:12:54:733 [Appium] New Mac2Driver session created successfully, session 0a732e24-1c73-4dc0-b796-ff6f241e34ee added to master session list
2021-08-15 12:12:54:734 [BaseDriver] Event 'newSessionStarted' logged at 1629029574734 (19:12:54 GMT+0700 (Indochina Time))
2021-08-15 12:12:54:735 [W3C (0a732e24)] Cached the protocol value 'W3C' for the new session 0a732e24-1c73-4dc0-b796-ff6f241e34ee
2021-08-15 12:12:54:735 [W3C (0a732e24)] Responding to client with driver.createSession() result: {"capabilities":{"platformName":"mac","automationName":"mac2","newCommandTimeout":30000,"bundleId":"com.mycompany"}}
2021-08-15 12:12:54:737 [HTTP] <-- POST /wd/hub/session 200 7022 ms - 182
2021-08-15 12:12:54:737 [HTTP] 
2021-08-15 12:12:54:741 [HTTP] --> POST /wd/hub/session/0a732e24-1c73-4dc0-b796-ff6f241e34ee/element
2021-08-15 12:12:54:741 [HTTP] {"using":"xpath","value":"//XCUIElementTypeTextField[@placeholderValue='User Name']"}
2021-08-15 12:12:54:744 [W3C (0a732e24)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeTextField[@placeholderValue='User Name']","0a732e24-1c73-4dc0-b796-ff6f241e34ee"]
2021-08-15 12:12:54:745 [BaseDriver] Valid locator strategies for this request: id, name, accessibility id, xpath, class name, -ios predicate string, predicate string, -ios class chain, class chain
2021-08-15 12:12:54:746 [WD Proxy] Matched '/element' to command name 'findElement'
2021-08-15 12:12:54:747 [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:10100/session/8328BD9E-22C9-4868-88D4-6B81113F6203/element] with body: {"using":"xpath","value":"//XCUIElementTypeTextField[@placeholderValue='User Name']"}
2021-08-15 12:12:55:073 [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"35EF4B04-677C-4908-B428-9F8D49538B27","element-6066-11e4-a52e-4f735466cecf":"35EF4B04-677C-4908-B428-9F8D49538B27"},"sessionId":"8328BD9E-22C9-4868-88D4-6B81113F6203"}
2021-08-15 12:12:55:073 [W3C (0a732e24)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"35EF4B04-677C-4908-B428-9F8D49538B27","ELEMENT":"35EF4B04-677C-4908-B428-9F8D49538B27"}
2021-08-15 12:12:55:074 [HTTP] <-- POST /wd/hub/session/0a732e24-1c73-4dc0-b796-ff6f241e34ee/element 200 332 ms - 137
2021-08-15 12:12:55:074 [HTTP] 
2021-08-15 12:13:01:506 [HTTP] --> POST /wd/hub/session/0a732e24-1c73-4dc0-b796-ff6f241e34ee/execute/sync
2021-08-15 12:13:01:506 [HTTP] {"script":"return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k<arguments.length;k++)e[k-2]=arguments[k];return a.prototype[c].apply(b,e)}})();var m=\"unknown error\",l={15:\"element not selectable\",11:\"element not visible\"};l[31]=m;l[30]=m;l[24]=\"invalid cookie domain\";l[29]=\"invalid element coordinates\";l[12]=\"invalid element state\";l[32]=\"invalid selector\";l[51]=\"invalid selector\";\nl[52]=\"invalid selector\";l[17]=\"javascript error\";l[405]=\"unsupported operation\";l[34...
2021-08-15 12:13:01:513 [W3C (0a732e24)] Calling AppiumDriver.execute() with args: ["return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k<arguments.length;k++)e[k-2]=arguments[k];return a.prototype[c].apply(b,e)}})();var m=\"unknown error\",l={15:\"element not selectable\",11:\"element not visible\"};l[31]=m;l[30]=m;l[24]=\"invalid cookie domain\";l[29]=\"invalid element coordinates\";l[12]=\"invalid element state\";l[32]=\"invalid selector\";l[51]=\"invalid selector\";\nl[52]=\"invalid selector\";l[17]=\"javascript error\";l[405]=\"unsupported operation\";l[34]=\"move ...
2021-08-15 12:13:01:575 [W3C (0a732e24)] Encountered internal error running command: NotImplementedError: Method is not implemented
2021-08-15 12:13:01:575 [W3C (0a732e24)]     at Mac2Driver.execute (/usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/lib/commands/execute.js:38:9)
2021-08-15 12:13:01:575 [W3C (0a732e24)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
2021-08-15 12:13:01:575 [W3C (0a732e24)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:137:12
2021-08-15 12:13:01:575 [W3C (0a732e24)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:261:31)
2021-08-15 12:13:01:575 [W3C (0a732e24)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:136:9)
2021-08-15 12:13:01:575 [W3C (0a732e24)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:152:3)
2021-08-15 12:13:01:575 [W3C (0a732e24)]     at Mac2Driver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
2021-08-15 12:13:01:575 [W3C (0a732e24)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:563:36)
2021-08-15 12:13:01:575 [W3C (0a732e24)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-08-15 12:13:01:575 [W3C (0a732e24)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
2021-08-15 12:13:01:577 [HTTP] <-- POST /wd/hub/session/0a732e24-1c73-4dc0-b796-ff6f241e34ee/execute/sync 405 71 ms - 1206
2021-08-15 12:13:01:577 [HTTP] 

## Code To reproduce the issue

desired_caps = {
        "platformName": "mac",
        "appium:automationName": "mac2",
        "appium:newCommandTimeout": 30000,
        "appium:bundleId": "com.mycompany"
    }
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
ele = driver.find_element(By.XPATH, "//XCUIElementTypeTextField[@placeholderValue='User Name']")
attr = ele.get_attribute("enabled")
print(attr)

**Comment by thinhndfloware** [comment]
Update from Appium Java client, I can get the attribute of the element successfully as the screenshot.

![image](https://user-images.githubusercontent.com/67256035/129478592-f48e9b25-6480-493e-a8d4-2f64dd1039b9.png)

**Comment by thinhndfloware** [comment]
I've corrected the import webdriver from the appium library (not from selenium). The issue is invalid now and I would like to close it.
