### ISSUE TITLE
通过pycharm卸载Appium-Python-Client，再次安装报错

### ISSUE THREAD

**Issue by okhit007** [appium/python-client#683]
在pycharm--库管理删除 Appium-Python-Client 库后，再次pip安装，报错。python版本是3.10，错误如下：

    copying appium/webdriver/extensions/search_context/windows.py -> build/lib/appium/webdriver/extensions/search_context
      copying appium/webdriver/py.typed -> build/lib/appium/webdriver
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/f4/r5g2s4bn1q953575tn9c0ds00000gn/T/pip-install-wvta7hr8/appium-python-client_2944f54d8dec4fee9f1ae33159f70de1/setup.py", line 21, in <module>
          setup(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/command/install.py", line 568, in run
          self.run_command('build')
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/build_py.py", line 56, in run
          self.build_package_data()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/build_py.py", line 127, in build_package_data
          srcfile in self.distribution.convert_2to3_doctests):
      AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests'

有人可以帮忙看看怎么回事么，谢谢~~thx~

**Comment by okhit007** [comment]
解决了，降低setuptools版本就行了~~
