### ISSUE TITLE
Install python-client failed in windows 10 because of ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by jxliaocb** [appium/python-client#769]
## The problem

Install  python-client failed with Master branch on window 10.
After run ` python setup.py install`,  raised the following exception:

Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    install_requires=['selenium ~= 4.1'],
  File "C:\vnstudio\lib\site-packages\setuptools\__init__.py", line 155, in setup       
    return distutils.core.setup(**attrs)
  File "C:\vnstudio\lib\site-packages\setuptools\_distutils\core.py", line 109, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\vnstudio\lib\site-packages\setuptools\dist.py", line 462, in __init__
    for k, v in attrs.items()
  File "C:\vnstudio\lib\site-packages\setuptools\_distutils\dist.py", line 293, in __init__
    self.finalize_options()
  File "C:\vnstudio\lib\site-packages\setuptools\dist.py", line 850, in finalize_options
    for ep in sorted(loaded, key=by_order):
  File "C:\vnstudio\lib\site-packages\setuptools\dist.py", line 849, in <lambda>
    loaded = map(lambda e: e.load(), filtered)
  File "C:\vnstudio\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "C:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\vnstudio\lib\site-packages\py2app\build_app.py", line 37, in <module>
    from py2app.create_appbundle import create_appbundle
  File "C:\vnstudio\lib\site-packages\py2app\create_appbundle.py", line 9, in <module>
    from py2app.util import make_exec, makedirs, mergecopy, mergetree, skipscm
  File "C:\vnstudio\lib\site-packages\py2app\util.py", line 5, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
##

**Comment by KazuCocoa** [comment]
it seems like the selenium dependency has the fcntl, which is not work on Win.
Did it occur only via `python setup.py install`? I wonder if the general pip install also has this error message

**Comment by jxliaocb** [comment]
@KazuCocoa  Yes. It's same with pip install Appium-Python-Client

PS C:\projects\python-client> pip uninstall Appium-Python-Client
Found existing installation: Appium-Python-Client 1.3.0
Uninstalling Appium-Python-Client-1.3.0:
  Would remove:
    c:\vnstudio\lib\site-packages\appium\*
    c:\vnstudio\lib\site-packages\appium_python_client-1.3.0.dist-info\*
Proceed (Y/n)? y
  Successfully uninstalled Appium-Python-Client-1.3.0
PS C:\projects\python-client> pip install Appium-Python-Client  
Collecting Appium-Python-Client
  Using cached Appium-Python-Client-2.6.2.tar.gz (118 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jxlia\AppData\Local\Temp\pip-install-76onv8ny\appium-python-client_adbd07dde988454cb6995bb12f2c0063\setup.py", line 51, in <module>   
          install_requires=['selenium ~= 4.1'],
        File "C:\vnstudio\lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\vnstudio\lib\site-packages\setuptools\_distutils\core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\vnstudio\lib\site-packages\setuptools\dist.py", line 462, in __init__
          for k, v in attrs.items()
        File "C:\vnstudio\lib\site-packages\setuptools\_distutils\dist.py", line 293, in __init__
          self.finalize_options()
        File "C:\vnstudio\lib\site-packages\setuptools\dist.py", line 850, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "C:\vnstudio\lib\site-packages\setuptools\dist.py", line 849, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "C:\vnstudio\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 194, in load
          module = import_module(match.group('module'))
        File "C:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "C:\vnstudio\lib\site-packages\py2app\build_app.py", line 37, in <module>
          from py2app.create_appbundle import create_appbundle
        File "C:\vnstudio\lib\site-packages\py2app\create_appbundle.py", line 9, in <module>
          from py2app.util import make_exec, makedirs, mergecopy, mergetree, skipscm
        File "C:\vnstudio\lib\site-packages\py2app\util.py", line 5, in <module>
          import fcntl
      ModuleNotFoundError: No module named 'fcntl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details

**Comment by jxliaocb** [comment]
Solved.  Remove py2app with `pip unistall py2app` because py2app  is not support Windows.
