### ISSUE TITLE
Is there a way to get iOS Log?

### ISSUE THREAD

**Issue by ChenFromNB** [appium/python-client#80]
Our team use Appium to develop the iOS automation.Now we want to get iOS logs after running App by Appium. Howerer, we don't find a way to get iOS logs which is appeared in Xcode console when debuging project. Android has 'adb logcat', is there is a way like 'adb logcat' in Appium?

**Comment by imurchie** [comment]
You can run the server with `--show-ios-log` to get the iOS logs interspersed with the Appium server logs.

You can also use `driver.log_types` (see [here](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L853)) to get the available log types, and `logs = driver.get_log(type)` (see [here](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L862) to get the actual logs for a particular type.

**Comment by Tracydeng** [comment]
@imurchie   when I use `appium --show-ios-log`  and client with `self.driver.get_log('server')`,it's throw errors with:
``WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unsupported log type 'server' for this device. Supported types : {"syslog":"System Logs - Device logs for iOS applications on real devices and simulators","crashlog":"Crash Logs - Crash reports for iOS applications on real devices and simulators","performance":"Performance Logs - Debug Timelines on real devices and simulators"}``

**Comment by imurchie** [comment]
Yes, "server" is not a valid log type. Look in the error message. There are only three types listed there.

**Comment by Tracydeng** [comment]
I also had a try with `performance` to get the applictaion's log, it's throw errors with:

``File "/Users/iSteven/iSteven/appium/FFTest/FFTestCases/register/FFregister.py", line 98, in test_Mobileregister
    appiumLogs = self.driver.get_log('performance')
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 969, in get_log
    return self.execute(Command.GET_LOG, {'type': log_type})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'getLogs' of undefined``
but successful for `syslog`

**Comment by imurchie** [comment]
Can you provide the Appium server logs? Then this can be fixed. Thanks!

**Comment by Tracydeng** [comment]
@imurchie 
[debug] [MJSONWP] Calling AppiumDriver.getLog() with args: ["performance","e903af0e-d986-41a3-b501-4fbadf8ea818"]
[debug] [XCUITest] Executing command 'getLog'
[debug] [iOS] Retrieving 'performance' logs
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'getLogs' of undefined
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/logging.js:34:38)
    at tryCatch (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as getLog] (../../../lib/commands/logging.js:34:11)
    at ../../../lib/basedriver/driver.js:173:24
    at tryCatcher (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.2.11.0@bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.2.11.0@bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.2.11.0@bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.2.11.0@bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.2.11.0@bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.2.11.0@bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.2.11.0@bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
[HTTP] <-- POST /wd/hub/session/e903af0e-d986-41a3-b501-4fbadf8ea818/log 500 30 ms - 214 
[HTTP] --> GET /wd/hub/session/e903af0e-d986-41a3-b501-4fbadf8ea818/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/e903af0e-d986-41a3-b501-4fbadf8ea818/screenshot] to [GET http://localhost:8100/session/B30B5327-0201-4311-BBF2-00C15EBE6446/screenshot] with body: {}

**Comment by imurchie** [comment]
Hmmm. Yes, that seems like an error. Can you create an issue on the Appium server repository: https://github.com/appium/appium/issues

**Comment by Tracydeng** [comment]
done
 https://github.com/appium/appium/issues/7986
