### ISSUE TITLE
 How to set the intentFlags parameter of start_activity?

### ISSUE THREAD

**Issue by chuihairu** [appium/python-client#846]
## The problem

I don't know how to set the value of intentFlags, I didn't find it on the documentation. 

## Environment
- Appium version :  `2.0.0-beta.57`
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: `Windows 11`
- Node.js version (unless using Appium.app|exe): `v18.14.0`
- Mobile platform/version under test: `Android 9`
- Real device or emulator/simulator: `emulator`
- Appium CLI or Appium.app|exe: `appium cli`

## Details

my code:

```python3
driver.start_activity(app_package,activity,intent_flags="FLAG_ACTIVITY_CLEAR_TOP",optional_intent_arguments="--es itemId 12345")
```
but it can't work well.

error log:

```
Exception occurred while executing:
java.lang.NumberFormatException: For input string: "FLAG_ACTIVITY_CLEAR_TOP"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.valueOf(Integer.java:775)
        at java.lang.Integer.decode(Integer.java:1232)
        at android.content.Intent.parseCommandArgs(Intent.java:6828)
        at com.android.server.am.ActivityManagerShellCommand.makeIntent(ActivityManagerShellCommand.java:306)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:374)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16238)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3593)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3308)
        at android.os.Binder.execTransact(Binder.java:731)

        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
        at android.os.ShellCommand.exec(ShellCommand.java:103)        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16238)        at android.os.Binder.shellCommand(Binder.java:634)        at android.os.Binder.onTransact(Binder.java:532)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3593)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3308)
        at android.os.Binder.execTransact(Binder.java:731)

    at getResponseForW3CError (C:\Users\cui\Workspaces\scripts\node_modules\@appium\base-driver\lib\protocol\errors.js:1067:9)
    at asyncHandler (C:\Users\cui\Workspaces\scripts\node_modules\@appium\base-driver\lib\protocol\protocol.js:476:57)
```
The following code does not report an error：

```python3
driver.start_activity(app_package,activity,intent_flags="0x04000000",optional_intent_arguments="--es itemId 12345")
```

## Link to Appium Logs

```
Exception occurred while executing:
java.lang.NumberFormatException: For input string: "FLAG_ACTIVITY_CLEAR_TOP"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.valueOf(Integer.java:775)
        at java.lang.Integer.decode(Integer.java:1232)
        at android.content.Intent.parseCommandArgs(Intent.java:6828)
        at com.android.server.am.ActivityManagerShellCommand.makeIntent(ActivityManagerShellCommand.java:306)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:374)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16238)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3593)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3308)
        at android.os.Binder.execTransact(Binder.java:731)

        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
        at android.os.ShellCommand.exec(ShellCommand.java:103)        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16238)        at android.os.Binder.shellCommand(Binder.java:634)        at android.os.Binder.onTransact(Binder.java:532)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3593)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3308)
        at android.os.Binder.execTransact(Binder.java:731)

    at getResponseForW3CError (C:\Users\cui\Workspaces\scripts\node_modules\@appium\base-driver\lib\protocol\errors.js:1067:9)
    at asyncHandler (C:\Users\cui\Workspaces\scripts\node_modules\@appium\base-driver\lib\protocol\protocol.js:476:57)
```

## Code To reproduce issue

```python3
driver.start_activity(app_package,activity,intent_flags="FLAG_ACTIVITY_CLEAR_TOP",optional_intent_arguments="--es itemId 12345")
```

**Comment by chuihairu** [comment]
Thanks
