### ISSUE TITLE
python appium's start_activity function generates an error, it inserted an extra /

### ISSUE THREAD

**Issue by wuminmin** [appium/python-client#851]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by wuminmin** [comment]
code:

import config, dito, tool, datetime

driver = config.driver


print('app start')
app_start_time = datetime.datetime.now()

dito.dito_login(driver)

driver.start_activity('com.mydito', '.ui.load.LoadActivity')






error log:

PS D:\WMM\github\android-auto-test> py .\test.py
Traceback (most recent call last):
  File "D:\WMM\github\android-auto-test\test.py", line 1, in <module>
    import config, dito, tool, datetime
  File "D:\WMM\github\android-auto-test\config.py", line 16, in <module>
    driver = webdriver.Remote("http://127.0.0.1:4723/wd/hub", caps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wmm\AppData\Local\Programs\Python\Python311\Lib\site-packages\appium\webdriver\webdriver.py", line 234, in __init__
    super().__init__(
  File "C:\Users\wmm\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\wmm\AppData\Local\Programs\Python\Python311\Lib\site-packages\appium\webdriver\webdriver.py", line 324, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wmm\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\wmm\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response  
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start
 the 'com.mydito' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for trouble
shooting. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\wmm\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 50
37 -s emulator-5554 shell am start -W -n com.mydito/com.mydito.ui.load.LoadActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 255'; Command output:
Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.mydito/.ui.load.LoadActivity } from null (pid=28458, uid=2000) not exported from uid 10124
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1032)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:999)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:669)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAndWait(ActivityTaskManagerService.java:1338)
        at com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:3687)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:539)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:186)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10521)
        at android.os.Binder.onTransact(Binder.java:813)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5027)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2883)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)

    at getResponseForW3CError (C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
PS D:\WMM\github\android-auto-test>


we can see 'C:\\Users\\wmm\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 50
37 -s emulator-5554 shell am start -W -n com.mydito/com.mydito.ui.load.LoadActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 255'

the '/' in 'com.mydito/com.mydito.ui.load.LoadActivity' is superfluous.


my pip lsit:
PS D:\WMM\github\android-auto-test> pip list
Package                  Version
------------------------ -----------
aiohttp                  3.8.4
aiosignal                1.3.1
apiclient                1.0.4
Appium-Python-Client     2.9.0
APScheduler              3.6.0
asgiref                  3.6.0
astor                    0.8.0
async-generator          1.10
async-timeout            4.0.2
attrs                    22.2.0
beautifulsoup4           4.11.2
bleach                   3.1.0
bs4                      0.0.1
certifi                  2022.12.7
cffi                     1.15.1
charset-normalizer       3.1.0
colorama                 0.4.6
cycler                   0.10.0
Django                   4.1.7
frozenlist               1.3.3
gast                     0.2.2
google-api-python-client 1.6.7
google-pasta             0.1.7
h11                      0.14.0
httplib2                 0.22.0
idna                     3.4
lxml                     4.9.2
multidict                6.0.4
numpy                    1.24.2
oauth2client             4.1.3
openai                   0.27.2
opencv-python            4.7.0.72
outcome                  1.2.0
packaging                23.0
Pillow                   9.5.0
pip                      23.0.1
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.21
pyparsing                3.0.9
PySocks                  1.7.1
pytesseract              0.3.10
python-docx              0.8.11
pytz                     2022.7.1
pytz-deprecation-shim    0.1.0.post0
reportlab                3.6.12
requests                 2.28.2
rsa                      4.9
selenium                 4.8.2
setuptools               65.5.0
six                      1.16.0
sniffio                  1.3.0
sortedcontainers         2.4.0
soupsieve                2.4
sqlparse                 0.4.3
tesseract                0.1.3
tqdm                     4.65.0
trio                     0.22.0
trio-websocket           0.9.2
tzdata                   2022.7
tzlocal                  4.2
uritemplate              3.0.1
urllib3                  1.26.14
webencodings             0.5.1
wsproto                  1.2.0
yarl                     1.8.2

**Comment by jlipps** [comment]
this error comes from the appium server and is not a python client issue. also, the error appears to come all the way from android / adb. are you able to run the adb command manually successfully?

**Comment by wuminmin** [comment]
also can not run cammand successfully

**Comment by KazuCocoa** [comment]
> com.mydito/.ui.load.LoadActivity

Is it launchable activity?

**Comment by wuminmin** [comment]
can not lauch

**Comment by KazuCocoa** [comment]
Then, the behavior is expected because of the Android thing. The activity should have intent filter such as https://github.com/appium/android-apidemos/blob/master/app/src/main/AndroidManifest.xml#L126 to start it via adb start.

**Comment by KazuCocoa** [comment]
Close as not the client specific issue
