### ISSUE TITLE
ModuleNotFoundError: No module named 'appium'

### ISSUE THREAD

**Issue by DamianBachasingh** [appium/python-client#860]
## The problem
ModuleNotFoundError: No module named 'appium'

## Environment
- Appium version = latest
- Desktop OS = Windows
- Python = 3.9 64 bit

## Details

C:\Windows\system32>pip install Appium-Python-Client
Collecting Appium-Python-Client
  Using cached Appium-Python-Client-2.9.0.tar.gz (3.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Damian\AppData\Local\Temp\pip-install-lfe0x6i1\appium-python-client_e3ad30d50f5440a8ba46cbf2082ca1c8\setup.py", line 19, in <module>
          from appium.common.helper import library_version
      ModuleNotFoundError: No module named 'appium'
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Does anyone know how to resolve this issue?

**Comment by DamianBachasingh** [comment]
The virtual environment on which this is being run has internet access to install pip packages, but maybe it also needs internet access to appium to properly run setup.py?
