### ISSUE TITLE
When the network is normal, why will there be an error when using python code to open the app

### ISSUE THREAD

**Issue by hyytest** [appium/python-client#942]
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Python39\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Python39\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Python39\lib\http\client.py", line 1371, in getresponse
    response.begin()
  File "D:\Python39\lib\http\client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "D:\Python39\lib\http\client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-87533e18bd6d>", line 1, in <cell line: 1>
    runfile('E:/python/pythonProject/reptile/spider/app.py', wdir='E:/python/pythonProject/reptile/spider')
  File "D:\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/python/pythonProject/reptile/spider/app.py", line 151, in <module>
    el1 = driver.find_element(By.ID, "com.microsoft.emmx:id/search_box_text")
  File "D:\Python39\lib\site-packages\appium\webdriver\webdriver.py", line 384, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']
  File "D:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python39\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 300, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python39\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 321, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "D:\Python39\lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
  File "D:\Python39\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "D:\Python39\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\Python39\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\Python39\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\Python39\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "D:\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Python39\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Python39\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Python39\lib\http\client.py", line 1371, in getresponse
    response.begin()
  File "D:\Python39\lib\http\client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "D:\Python39\lib\http\client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by KazuCocoa** [comment]
Please attach the full appium log and the python client's create session log as well? I guess you ran the test script/appium on local Appium server, but to check more contexts.

**Comment by hyytest** [comment]
> Please attach the full appium log and the python client's create session log as well? I guess you ran the test script/appium on local Appium server, but to check more contexts.

from appium import webdriver
from appium.webdriver.common.touch_action import TouchAction
from appium.options.android import UiAutomator2Options
import time

def swipeUp(driver,n = 3):
    x1 = width*0.5
    y1 = height*0.8
    y2 = height*0.25
    time.sleep(3)
    for i in range(n):
        time.sleep(3)
        driver.swipe(x1, y1, x1, y2)

def swipeDown(driver,n = 5):
    x1 = width*0.5
    y1 = height*0.26
    y2 = height*0.9
    time.sleep(3)
    for i in range(n):
        time.sleep(3)
        driver.swipe(x1, y1, x1, y2)

capabilities = dict(
    platformName= "Android",
    platformVersion= "6",
    deviceName= "hyy",
    appPackage= "com.android.chrome",
    appActivity= "org.chromium.chrome.browser.ChromeTabbedActivity",
    adbExecTimeout=30000,
    noReset= True,
)

appium_server_url = 'http://localhost:4723/wd/hub'
for i in range (1,3):
    time.sleep(3)
    capabilities_options = UiAutomator2Options().load_capabilities(capabilities)
    driver = webdriver.Remote(command_executor=appium_server_url, options=capabilities_options)
    size = driver.get_window_size()
    print(size)
    driver.get("https://youtube.com/")#There will be an error after executing this
    width = size['width']
    height = size['height']
     time.sleep(3)
    swipeUp(driver,2)
    time.sleep(3)
    driver.quit()

**Comment by hyytest** [comment]
> Please attach the full appium log and the python client's create session log as well? I guess you ran the test script/appium on local Appium server, but to check more contexts.
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-87533e18bd6d>", line 1, in <cell line: 1>
    runfile('E:/python/pythonProject/reptile/spider/app.py', wdir='E:/python/pythonProject/reptile/spider')
  File "D:\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/python/pythonProject/reptile/spider/app.py", line 148, in <module>
    driver.get("https://youtube.com/")
  File "D:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in get
    self.execute(Command.GET, {"url": url})
  File "D:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "D:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 125, in check_response
    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error attempting to start URI. Original error: Error: Error executing adbExec. Original error: 'Command 'D:\\SDK\\androidsdk\\platform-tools\\adb.exe -P 5037 -s FDGNW17113001644 shell am start -W -a android.intent.action.VIEW -d https\://youtube.com/ com.android.chrome' timed out after 30000ms'. Try to increase the 30000ms adb execution timeout represented by 'adbExecTimeout' capability
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Error attempting to start URI. Original error: Error: Error executing adbExec. Original error: 'Command 'D:\\SDK\\androidsdk\\platform-tools\\adb.exe -P 5037 -s FDGNW17113001644 shell am start -W -a android.intent.action.VIEW -d https\://youtube.com/ com.android.chrome' timed out after 30000ms'. Try to increase the 30000ms adb execution timeout represented by 'adbExecTimeout' capability
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)

**Comment by Ffmydy** [comment]
遇到同样问题

**Comment by Ffmydy** [comment]
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
