### ISSUE TITLE
Appium driver's terminate_app method throwing NotYetImplementedError

### ISSUE THREAD

**Issue by MagdelineNg** [appium/python-client#943]
## The problem
When trying to use driver.terminate_app(bundle_id), I receive an error 
```
selenium.common.exceptions.UnknownMethodException: Message: Method has not yet been implemented
Stacktrace:
NotYetImplementedError: Method has not yet been implemented
```

Logs:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/appium/webdriver/extensions/applications.py", line 131, in remove_app
    self.assert_extension_exists(ext_name).execute_script(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/appium/webdriver/errorhandler.py", line 125, in check_response
    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
selenium.common.exceptions.UnknownMethodException: Message: Method is not implemented
Stacktrace:
NotImplementedError: Method is not implemented
    at Mac2Driver.execute (/Users/usr1/.appium/node_modules/appium-mac2-driver/lib/commands/execute.js:46:9)
    at commandExecutor (/Users/usr1/node_modules/@appium/base-driver/lib/basedriver/driver.ts:107:18)
    at /Users/usr1/node_modules/async-lock/lib/index.js:171:12
    at AsyncLock._promiseTry (/Users/usr1/node_modules/async-lock/lib/index.js:304:31)
    at exec (/Users/usr1/node_modules/async-lock/lib/index.js:170:9)
    at AsyncLock.acquire (/Users/usr1/node_modules/async-lock/lib/index.js:187:3)
    at Mac2Driver.executeCommand (/Users/usr1/node_modules/@appium/base-driver/lib/basedriver/driver.ts:123:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:723:14)
    at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:829:16)
    at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:735:17)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:19)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/usr1/Desktop/appium/testapp.py", line 211, in <module>
    driver.remove_app(BUNDLE_ID)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/appium/webdriver/extensions/applications.py", line 144, in remove_app
    self.mark_extension_absence(ext_name).execute(Command.REMOVE_APP, data)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/appium/webdriver/errorhandler.py", line 125, in check_response
    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
selenium.common.exceptions.UnknownMethodException: Message: Method has not yet been implemented
Stacktrace:
NotYetImplementedError: Method has not yet been implemented
    at Mac2Driver.executeCommand (/Users/usr1/node_modules/@appium/base-driver/lib/basedriver/driver.ts:101:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:723:14)
    at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:829:16)
    at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:735:17)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:19)

## Environment
Using Mac2 Driver with Appium Python Client

## Code To reproduce issue

```
from appium import webdriver as appium_webdriver
from appium.options.mac import Mac2Options
from appium.webdriver.appium_service import AppiumService
from appium.webdriver.common.appiumby import AppiumBy
from selenium import webdriver as selenium_webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

APPIUM_PORT = '4723'
APPIUM_HOST = '127.0.0.1'
BUNDLE_ID = "com.company.app"

driver = appium_webdriver.Remote(f"http://{APPIUM_HOST}:{APPIUM_PORT}", options=options)

#some driver actions
driver.remove_app(BUNDLE_ID)
```

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-mac2-driver?tab=readme-ov-file#macos-terminateapp should help.

Python client send `mobile: terminaApp` first, then fallback to the old one, but both did not exist in the mac2 driver, thus the error was raised.
https://github.com/appium/python-client/blob/40ac0127353ebe6dd0b235e6e1916f53d862d52e/appium/webdriver/extensions/applications.py#L147C9-L147C22

The `macos:` extension command should help for mac2 driver.
