### ISSUE TITLE
webelement.rect cause WebDriverException: Message: That URL did not map to a valid JSONWP resource

### ISSUE THREAD

**Issue by 2kpurple** [appium/python-client#95]
Error
Traceback (most recent call last):
  File "/home/purplek/Programming/python/appium/JDTest.py", line 34, in test
    self.searchProduct('test')
  File "/home/purplek/Programming/python/appium/JDTest.py", line 42, in search
    self.getSearchList(1)
  File "/home/purplek/Programming/python/appium/JDTest.py", line 48, in getList
    start_item = search_items[0].rect
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 367, in rect
    return self._execute(Command.GET_ELEMENT_RECT)['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 404, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 195, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
WebDriverException: Message: That URL did not map to a valid JSONWP resource

"start_item = search_items[0].rect" cause WebDriverException: Message: That URL did not map to a valid JSONWP resource

how to fix it?

I use appium in Android 4.3

**Comment by imurchie** [comment]
Thanks! 

This is a server issue. I've opened an issue there (appium/appium#5369) that you can watch for developments.
